import sys


# Create a list containing a series of numbers stopping when a limit is reached.
# This series is generated by repeating a formula.
# Beginning with the values a = 1 and b = 2
# add them together c = a + b
# then copy b to a and then copy c to b
# and repeat print each successive value of a
# e.g. The first ten values as a list would be: [1,1,2,3,5,8,13,21,34,55]


def get_fibonacci_numbers_list(limit):
    output = []

    # your code here
    a = 1
    b = 1

    while limit > 0:
        output.append(a)

        c = a + b
        a = b
        b = c

        limit -= 1

    return output


# run the code passing in 10 as a parameter
result = get_fibonacci_numbers_list(10)

print(result)

# test
assert result == [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
