# Create a list containing a series of numbers stopping when a limit is reached.
# This series is generated by repeating a formula.
# Beginning with the values a = 1 and b = 2
# add them together c = a + b
# then copy b to a and then copy c to b
# and repeat print each successive value of a
# e.g. The first ten values as a list would be:
#  [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


def get_fibonacci_numbers_list(limit):

    output = []

    # your code here

    return output


result = get_fibonacci_numbers_list(10)

print(result)

assert result == [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
